resources:
- repo: self
  clean: true

pool:
  vmImage: 'ubuntu-latest'

variables:
    BuildConfiguration: 'Release'

trigger:
  batch: true

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'dev-acr'
- task: Docker@2
  displayName: 'Build an image'
  inputs:
    buildContext: '.'
    containerRegistry: 'dev-acr'
    repository: 'pipelines-dotnet-core-docker'
    Dockerfile: Dockerfile
    tags: |
     $(Build.BuildId)
     latest
    addPipelineData: false

